#!/usr/bin/env bash
# Script that transfers a file from our client to a server
if [ "$#" -lt 4]
then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path="$1"
	ip="$2"
	username="$3"
	ssh_path="$4"
	scp -o StrictHostKeyChecking=no -i $ssh_path $file_path $username@$ip:~
fi
