#!/usr/bin/env bash
#  script that configures a server to the above requirements

default="listen 8080 default_server;"
new="listen 80 default_server;"

sudo sed -i "s/$default/$new/" /etc/nginx/sites-enabled/default

sudo sed -i "22d" /etc/nginx/sites-enabled/default

sudo service nginx restart
